# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
fish_style_pwd_dir_length = 1

[git_status]
# windows_starship = ""

[status]
disabled = false
map_symbol = true

# Disabled modules

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
