#!/usr/bin/env zsh

# The location where our history will be stored
HISTFILE=$HOME/.zshhistory

# How many lines of history to store in the $HISTFILE
SAVEHIST=10000

# How many lines of history to store in the current session
HISTSIZE=10000

# Append history to the end of $HISTFILE instead of overwriting it, this enables
# multiple zsh instances to share a single $HISTFILE. It does this incremently
# as commands are executed so that they are all done in the order they were
# executed.
setopt inc_append_history

# Re-read the $HISTFILE before accessing the history within a shell. This
# enables the history of one shell to be reflected in the others immediately.
setopt share_history

# Store extended history information in the $HISTFILE.
setopt extended_history

# Only save one entry for adjacent duplicate commands.
setopt hist_ignore_dups

# Expire duplicate entries first, this allows the history to show more unique
# entries instead of having several thousand entries for common commands.
setopt hist_expire_dups_first

# Cleanup meaningless blank lines in the $HISTFILE
setopt hist_reduce_blanks

# Don't store function definitions in the shell history
setopt hist_no_functions

# Don't beep when the end of the history is reached
setopt no_hist_beep
