#!/usr/bin/env zsh

# Add the zsh-completions defintions
fpath=(/usr/local/share/zsh-completions $fpath)

# Load the completion engine and initalize it.
autoload -U compinit
compinit

# Allows you to move the cursor around the list of completions to select one.
zmodload -i zsh/complist

# Automatically use menu completion after the second consecutive request for
# completion, for example by pressing the TAB key repeatedly.
setopt auto_menu

# Complete from both ends if the cursor is in the middle of the line.
setopt complete_in_word

# If a completion with the cursor in the word was started and it results in only
# one match, the cursor is placed at the end of the word.
setopt always_to_end

# Case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Display colors in the completion menu.
zstyle ':completion:*' list-colors ''

# Use the menu style to enable using the arrow keys to select a completion
zstyle ':completion:*:*:*:*:*' menu select

# Style autocompleted for the kill command, this will make it easy to kill things
# which are running on the system by my user.
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*:*:*:*:processes' command "ps -o pid,user,command -w -w"

# Use caching so that commands like apt and dpkg complete are useable
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path ~/.cache/zsh

# Don't complete uninteresting users
zstyle ':completion:*:*:*:users' ignored-patterns \
        adm amanda apache at avahi avahi-autoipd beaglidx bin cacti canna \
        clamav daemon dbus distcache dnsmasq dovecot fax ftp games gdm \
        gkrellmd gopher hacluster haldaemon halt hsqldb ident junkbust kdm \
        ldap lp mail mailman mailnull man messagebus mldonkey mysql nagios \
        named netdump news nfsnobody nobody nscd ntp nut nx obsrun openvpn \
        operator pcap polkitd postfix postgres privoxy pulse pvm quagga radvd \
        rpc rpcuser rpm rtkit scard shutdown squid sshd statd svn sync tftp \
        usbmux uucp vcsa wwwrun xfs '_*'

# ... unless we really want to.
zstyle '*' single-ignored show
