#!/usr/bin/env zsh

# Automatically have cd act like pushd
setopt auto_pushd

# Ignore duplicate entries of a directory on the pushd stack.
setopt pushd_ignore_dups

# Reverse directory of popd
setopt pushd_minus
