#!/usr/bin/env zsh

WRAPPER_SCRIPT="$HOME/.pyenv/versions/$(cat $HOME/.pyenv/version | head -n 1)/bin/virtualenvwrapper.sh"

if [ -e "$WRAPPER_SCRIPT" ]
then
    # Define our location for where our virtual environments will be stored.
    WORKON_HOME=~/.virtualenvs

    # Define a named directory for virtualenvs
    v=$WORKON_HOME
    : ~v

    # Source the virtualenvwrapper script
    source "$WRAPPER_SCRIPT"

    # Define a zshexit function which will ensure that a temporary virtualenv
    # is deactivated before we exit the shell.
    zshexit() {
        if [[ -n $VIRTUAL_ENV && "$(basename $VIRTUAL_ENV)" =~ '^tmp-.+$' ]]; then
            deactivate
        fi
    }
fi

#clean up the namespace slightly by removing the checker function
unset -v WRAPPER_SCRIPT
